In [168]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
import joblib

In [169]:
Data = pd.read_csv("laptops.csv")

In [170]:
Data

,index,brand,Model,Price,Rating,processor_brand,processor_tier,num_cores,num_threads,ram_memory,...,secondary_storage_type,secondary_storage_capacity,gpu_brand,gpu_type,is_touch_screen,display_size,resolution_width,resolution_height,OS,year_of_warranty
0,1,tecno,Tecno Megabook T1 Laptop (11th Gen Core i3/ 8G...,23990,63,intel,core i3,2,4,8,...,No secondary storage,0,intel,integrated,False,15.6,1920,1080,windows,1
1,2,tecno,Tecno Megabook T1 Laptop (11th Gen Core i7/ 16...,35990,67,intel,core i7,4,8,16,...,No secondary storage,0,intel,integrated,False,15.6,1920,1080,windows,1
2,3,hp,HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen...,51100,73,amd,ryzen 5,6,12,8,...,No secondary storage,0,amd,dedicated,False,15.6,1920,1080,windows,1
3,4,acer,Acer Extensa EX214-53 Laptop (12th Gen Core i5...,39990,62,intel,core i5,12,16,8,...,No secondary storage,0,intel,integrated,False,14.0,1920,1080,windows,1
4,5,lenovo,Lenovo V15 82KDA01BIH Laptop (AMD Ryzen 3 5300...,28580,62,amd,ryzen 3,4,8,8,...,No secondary storage,0,amd,integrated,False,15.6,1920,1080,windows,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,998,asus,Asus Vivobook Pro 15 M6500QC-HN542WS Laptop (R...,65990,68,amd,ryzen 5,6,12,16,...,No secondary storage,0,nvidia,dedicated,False,15.6,1920,1080,windows,1
987,999,msi,MSI Thin GF63 12VE-070IN Gaming Laptop (12th G...,91990,73,intel,core i7,10,16,16,...,No secondary storage,0,nvidia,dedicated,False,15.6,1920,1080,windows,2
988,1000,asus,Asus Vivobook Go 15 2023 E1504FA-NJ522WS Lapto...,44990,59,amd,ryzen 5,4,8,8,...,No secondary storage,0,amd,integrated,False,15.6,1920,1080,windows,1
989,1001,asus,Asus Zenbook 14 2023 UM3402YA-KP541WS Laptop (...,67990,68,amd,ryzen 5,6,12,16,...,No secondary storage,0,amd,integrated,False,14.0,2560,1600,windows,1
990,1002,hp,HP Chromebook 15a-na0008TU Laptop (Intel Celer...,20990,37,intel,celeron,2,2,4,...,No secondary storage,0,intel,integrated,False,15.6,1366,768,chrome,1

In [171]:
Data.shape

(991, 22)

In [172]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 991 entries, 0 to 990
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   index                       991 non-null    int64
 1   brand                       991 non-null    object
 2   Model                       991 non-null    object
 3   Price                       991 non-null    int64
 4   Rating                      991 non-null    int64
 5   processor_brand             991 non-null    object
 6   processor_tier              991 non-null    object
 7   num_cores                   991 non-null    int64
 8   num_threads                 991 non-null    int64
 9   ram_memory                  991 non-null    int64
 10  primary_storage_type        991 non-null    object
 11  primary_storage_capacity    991 non-null    int64
 12  secondary_storage_type      991 non-null    object
 13  secondary_storage_capacity  991 non-null    int64
 14  gpu_brand                   991 non-null    object
 15  gpu_type                    991 non-null    object
 16  is_touch_screen             991 non-null    bool
 17  display_size                991 non-null    float64
 18  resolution_width            991 non-null    int64
 19  resolution_height           991 non-null    int64
 20  OS                          991 non-null    object
 21  year_of_warranty            991 non-null    object
dtypes: bool(1), float64(1), int64(10), object(10)
memory usage: 163.7+ KB

In [173]:
Data.isnull().sum()

index                         0
brand                         0
Model                         0
Price                         0
Rating                        0
processor_brand               0
processor_tier                0
num_cores                     0
num_threads                   0
ram_memory                    0
primary_storage_type          0
primary_storage_capacity      0
secondary_storage_type        0
secondary_storage_capacity    0
gpu_brand                     0
gpu_type                      0
is_touch_screen               0
display_size                  0
resolution_width              0
resolution_height             0
OS                            0
year_of_warranty              0
dtype: int64

In [174]:
X = Data.drop(["Model","Price","index"],axis=1)

In [175]:
X

,brand,Rating,processor_brand,processor_tier,num_cores,num_threads,ram_memory,primary_storage_type,primary_storage_capacity,secondary_storage_type,secondary_storage_capacity,gpu_brand,gpu_type,is_touch_screen,display_size,resolution_width,resolution_height,OS,year_of_warranty
0,tecno,63,intel,core i3,2,4,8,SSD,512,No secondary storage,0,intel,integrated,False,15.6,1920,1080,windows,1
1,tecno,67,intel,core i7,4,8,16,SSD,1024,No secondary storage,0,intel,integrated,False,15.6,1920,1080,windows,1
2,hp,73,amd,ryzen 5,6,12,8,SSD,512,No secondary storage,0,amd,dedicated,False,15.6,1920,1080,windows,1
3,acer,62,intel,core i5,12,16,8,SSD,512,No secondary storage,0,intel,integrated,False,14.0,1920,1080,windows,1
4,lenovo,62,amd,ryzen 3,4,8,8,SSD,512,No secondary storage,0,amd,integrated,False,15.6,1920,1080,windows,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,asus,68,amd,ryzen 5,6,12,16,SSD,512,No secondary storage,0,nvidia,dedicated,False,15.6,1920,1080,windows,1
987,msi,73,intel,core i7,10,16,16,SSD,512,No secondary storage,0,nvidia,dedicated,False,15.6,1920,1080,windows,2
988,asus,59,amd,ryzen 5,4,8,8,SSD,512,No secondary storage,0,amd,integrated,False,15.6,1920,1080,windows,1
989,asus,68,amd,ryzen 5,6,12,16,SSD,512,No secondary storage,0,amd,integrated,False,14.0,2560,1600,windows,1
990,hp,37,intel,celeron,2,2,4,HDD,128,No secondary storage,0,intel,integrated,False,15.6,1366,768,chrome,1

In [176]:
Y = Data["Price"]

In [177]:
Y

0      23990
1      35990
2      51100
3      39990
4      28580
       ...
986    65990
987    91990
988    44990
989    67990
990    20990
Name: Price, Length: 991, dtype: int64

In [178]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [179]:
X_train.shape

(792, 19)

In [180]:
X_test.shape

(199, 19)

In [181]:
Y_train.shape

(792,)

In [182]:
Y_test.shape

(199,)

In [183]:
X_train.select_dtypes("object")

,brand,processor_brand,processor_tier,primary_storage_type,secondary_storage_type,gpu_brand,gpu_type,OS,year_of_warranty
215,acer,intel,core i3,SSD,No secondary storage,intel,integrated,windows,1
294,lenovo,intel,core i5,SSD,No secondary storage,intel,integrated,windows,1
49,dell,amd,ryzen 5,SSD,No secondary storage,amd,integrated,windows,1
720,dell,intel,core i7,SSD,No secondary storage,nvidia,dedicated,windows,1
235,acer,intel,core i7,SSD,No secondary storage,nvidia,dedicated,windows,1
...,...,...,...,...,...,...,...,...,...
106,acer,amd,ryzen 5,SSD,No secondary storage,amd,integrated,windows,1
270,hp,amd,ryzen 5,SSD,No secondary storage,nvidia,dedicated,windows,1
860,dell,intel,core i5,SSD,No secondary storage,intel,integrated,windows,1
435,hp,intel,core i5,SSD,No secondary storage,intel,integrated,windows,1
102,hp,amd,ryzen 5,SSD,No secondary storage,amd,dedicated,windows,1

In [184]:
Cat_Cols = X_train.select_dtypes("object")

In [185]:
Cat_Cols

,brand,processor_brand,processor_tier,primary_storage_type,secondary_storage_type,gpu_brand,gpu_type,OS,year_of_warranty
215,acer,intel,core i3,SSD,No secondary storage,intel,integrated,windows,1
294,lenovo,intel,core i5,SSD,No secondary storage,intel,integrated,windows,1
49,dell,amd,ryzen 5,SSD,No secondary storage,amd,integrated,windows,1
720,dell,intel,core i7,SSD,No secondary storage,nvidia,dedicated,windows,1
235,acer,intel,core i7,SSD,No secondary storage,nvidia,dedicated,windows,1
...,...,...,...,...,...,...,...,...,...
106,acer,amd,ryzen 5,SSD,No secondary storage,amd,integrated,windows,1
270,hp,amd,ryzen 5,SSD,No secondary storage,nvidia,dedicated,windows,1
860,dell,intel,core i5,SSD,No secondary storage,intel,integrated,windows,1
435,hp,intel,core i5,SSD,No secondary storage,intel,integrated,windows,1
102,hp,amd,ryzen 5,SSD,No secondary storage,amd,dedicated,windows,1

In [186]:
Num_Cols = X_train.select_dtypes("int64","float64")

In [187]:
Num_Cols

,Rating,num_cores,num_threads,ram_memory,primary_storage_capacity,secondary_storage_capacity,resolution_width,resolution_height
215,57,6,8,8,512,0,1920,1080
294,57,8,12,16,512,0,1920,1080
49,66,6,12,8,512,0,1920,1080
720,88,14,20,32,1024,0,3456,2160
235,75,16,24,16,1024,0,1920,1200
...,...,...,...,...,...,...,...,...
106,60,6,12,16,512,0,1920,1080
270,71,6,12,8,512,0,1920,1080
860,63,4,8,8,512,0,1920,1080
435,64,10,12,8,512,0,1366,768
102,62,6,12,8,512,0,1920,1080

In [188]:
num_pipeline = Pipeline([
    ("Num",StandardScaler())
])

In [189]:
cat_pipeline = Pipeline([
    ("Cat",OneHotEncoder(handle_unknown = "ignore"))
])

In [190]:
full_pipeline = ColumnTransformer([
    ("num",num_pipeline,Num_Cols.columns),
    ("cat",cat_pipeline,Cat_Cols.columns)
])

In [191]:
X_train_prepared = full_pipeline.fit_transform(X_train)

In [192]:
X_test_prepared = full_pipeline.transform(X_test)

In [193]:
X_train_prepared.shape

(792, 74)

In [194]:
X_test_prepared.shape

(199, 74)

In [195]:
Lin_Reg = LinearRegression()

In [196]:
Lin_Reg.fit(X_train_prepared,Y_train)

LinearRegression()

In [197]:
Y_pred = Lin_Reg.predict(X_test_prepared)

In [198]:
RMSE = root_mean_squared_error
RMSE(Y_test,Y_pred)

20097.973306403444

In [199]:
DT = DecisionTreeRegressor()

In [200]:
DT.fit(X_train_prepared,Y_train)

DecisionTreeRegressor()

In [201]:
DT_Tree = DT.predict(X_test_prepared)

In [202]:
DT_Tree

array([105036.        ,  28190.        ,  65999.        ,  75499.        ,
        14990.        ,  89889.        ,  21990.        , 152990.        ,
        73990.        ,  45990.        ,  55990.        ,  57390.        ,
        12990.        ,  99990.        ,  51074.5       ,  47490.        ,
        48579.        ,  38171.        ,  62445.        ,  26999.        ,
        41990.        ,  39990.        ,  94990.        ,  62990.        ,
       100190.        ,  79690.        ,  49990.        , 119990.        ,
        60323.33333333,  24440.        , 121489.        ,  15990.        ,
       239299.        ,  41302.        ,  79990.        ,  37500.        ,
        83990.        ,  29990.        ,  56490.        ,  48990.        ,
        50591.        ,  50990.        ,  55900.        ,  15990.        ,
        37990.        ,  96990.        , 199990.        ,  87290.        ,
       141989.        ,  49990.        , 179990.        ,  73900.        ,
        42990.        ,  96729.        , 449990.        ,  65490.        ,
        66990.        , 143824.        ,  31490.        ,  43990.        ,
        62990.        ,  22990.        , 154999.        ,  89889.        ,
       239299.        ,  77846.33333333, 115990.        ,  43990.        ,
        92990.        ,  69990.        ,  65590.        , 105036.        ,
       260990.        ,  47990.        ,  59990.        ,  64500.        ,
        36800.        ,  27990.        ,  35990.        ,  46490.        ,
       187990.        ,  25390.        , 121489.        , 114990.        ,
       112990.        ,  94900.        ,  87990.        ,  63889.        ,
        36800.        , 100190.        ,  52990.        ,  94990.        ,
        55990.        , 132190.        , 269990.        ,  70190.        ,
        52244.5       , 113401.        ,  50990.        ,  99470.        ,
       144406.        ,  67990.        ,  44790.        , 139990.        ,
       141989.        ,  42499.        ,  36690.        ,  58269.        ,
       230060.        ,  70190.        ,  73990.        , 220990.        ,
        45990.        ,  71938.        , 119600.        ,  24990.        ,
        32550.        ,  47990.        , 164190.        ,  37500.        ,
        32890.        ,  63999.        ,  76499.        ,  91994.5       ,
        66990.        ,  40990.        ,  46490.        ,  67990.        ,
        86500.        , 165900.        ,  45990.        ,  51326.33333333,
       105490.        ,  75990.        ,  58269.        ,  75990.        ,
        38171.        ,  68800.        ,  51990.        ,  32490.        ,
        68800.        ,  34990.        ,  72990.        ,  50591.        ,
        43690.        ,  92990.        ,  41151.75      ,  25751.        ,
       249900.        ,  43990.        ,  99990.        ,  51326.33333333,
        43400.        ,  36800.        ,  42499.        ,  91994.5       ,
        48990.        ,  49990.        , 109990.        ,  56999.        ,
        43990.        ,  41151.75      ,  43990.        ,  44990.        ,
       129990.        ,  38171.        , 137490.        ,  62990.        ,
        65500.        ,  61712.        ,  64990.        ,  87990.        ,
        32990.        , 119990.        ,  46990.        ,  99990.        ,
        47650.        ,  46990.        , 132190.        ,  16490.        ,
        87990.        ,  64990.        ,  63990.        ,  73990.        ,
        43690.        ,  74990.        ,  88800.        ,  97990.        ,
        27990.        ,  66990.        , 249900.        ,  78100.        ,
        60323.33333333, 218990.        ,  69990.        ,  42499.        ,
        99990.        ,  32890.        ,  21990.        ])

In [203]:
RMSE(Y_test,DT_Tree)

31582.579370705895

In [204]:
Random_Forest = RandomForestRegressor()

In [205]:
RF = Random_Forest.fit(X_train_prepared,Y_train)

In [206]:
RF_PRED = RF.predict(X_test_prepared)

In [207]:
RF_PRED

array([120896.079     ,  26751.31      ,  63487.15666667,  64910.67666667,
        17716.06      ,  97048.82666667,  28758.62      , 162029.29      ,
        78199.82333333,  43525.98333333,  51405.1905    ,  72096.37      ,
        17401.95      ,  95373.33285714,  53343.38283333,  54501.72      ,
        48866.69654762,  40345.63      ,  62530.33261905,  29898.29      ,
        42850.83      ,  41344.46714286,  93346.715     ,  48207.99238095,
       117261.42      ,  72945.73666667,  61839.12333333, 113940.19      ,
        55742.34333333,  28105.98      , 188387.97      ,  20531.42      ,
       361799.42      ,  41211.77138095,  91656.1235    ,  36397.485     ,
       118052.45      ,  29909.3       ,  64418.33666667,  51019.97666667,
        54362.64      ,  54260.9047619 ,  56250.48595238,  18631.1       ,
        41569.215     , 104559.61      , 169318.18      ,  80315.43      ,
       296344.75      ,  49375.13      , 167656.19      ,  45997.68333333,
        33955.46      ,  97597.60471429, 232297.55      ,  83676.8       ,
        80713.74133333, 142104.76      ,  36997.03333333,  41033.99      ,
        44592.08583333,  20834.79      , 153229.46      ,  94657.81666667,
       281378.985     ,  79056.13578571, 114006.81      ,  71763.00666667,
        98604.8275    ,  70298.03333333,  63855.55666667, 112456.059     ,
       276528.63      ,  50373.64535714,  62943.88      ,  64727.54      ,
        25308.11      ,  27556.47      ,  35948.51809524,  49909.31166667,
       197881.1       ,  27586.59333333, 134288.23      , 116389.76      ,
       104681.48      ,  97459.17      ,  82382.69      ,  68490.76428571,
        25308.11      , 102065.48      ,  64664.74      ,  92207.19883333,
        51405.1905    , 141862.62666667, 269984.415     ,  71866.53333333,
        52350.53802381, 110071.543     ,  67430.97      , 100261.92      ,
       119454.635     ,  68062.79      ,  42954.43666667, 131211.33      ,
       241867.04      ,  51136.77      ,  36266.45      ,  56533.61666667,
       241612.11857143,  69556.29      ,  78849.74766667, 265119.535     ,
        44738.265     ,  74645.27      ,  68259.72333333,  32949.48666667,
        35798.28      ,  47263.46904762, 242979.11      ,  37480.80166667,
        36096.075     ,  63932.63      ,  79539.49      ,  98971.06333333,
        77573.22333333,  47028.58      ,  49668.26166667,  68062.79      ,
        81769.25      , 195048.29      ,  50873.79261905,  51285.69277778,
       102830.46      ,  69669.48333333,  70324.9       ,  69669.48333333,
        40562.00333333,  64918.41666667,  57602.42      ,  32665.36428571,
        65870.50666667,  57939.18666667,  70419.48      ,  54546.87      ,
        42066.145     , 102532.41066667,  40307.96322222,  21931.73      ,
       203108.34566667,  39651.67      , 108444.4       ,  53906.92083333,
        42879.25      ,  24200.42      ,  54358.14      , 113192.28666667,
        49709.        ,  50354.83261905, 106231.2855    ,  61057.46      ,
        40337.186     ,  36933.49469841,  40575.47533333,  45057.22666667,
       118074.385     ,  40345.63      , 140060.17      ,  44301.10404762,
        63372.31      ,  59488.61666667,  72545.23      ,  92492.51      ,
        29951.97666667, 114133.98333333,  51810.9       , 154141.47      ,
        45748.74      ,  45086.78738095, 141756.02666667,  20892.25      ,
        95710.78      ,  64403.47866667,  62083.50666667,  70633.24666667,
        42606.18      ,  83398.76      ,  89098.59      ,  75196.66383333,
        30752.98      ,  80713.74133333, 304172.59      ,  93177.33333333,
        57858.68333333, 135077.93333333,  67692.5       ,  53486.99      ,
       117419.55      ,  36096.075     ,  27076.73666667])

In [208]:
RMSE(Y_test,RF_PRED)

20558.7813699979

In [209]:
CV_Score = cross_val_score(RF,X_train_prepared,Y_train,scoring="neg_mean_squared_error",cv=10)

In [210]:
CV_RMSE = np.sqrt(-CV_Score).mean()

In [211]:
CV_RMSE

np.float64(21236.67473643461)

In [212]:
print("Linear_Regression :",RMSE(Y_test,Y_pred))
print("Decision Tree Classifier :",RMSE(Y_test,DT_Tree))
print("Random Forest :",RMSE(Y_test,RF_PRED))

Linear_Regression : 20097.973306403444
Decision Tree Classifier : 31582.579370705895
Random Forest : 20558.7813699979

In [213]:
best_model = RF

In [214]:
joblib.dump(best_model,"best_model.pkl")

['best_model.pkl']

In [216]:
joblib.dump(full_pipeline,"Full_Pipeline.pkl")

['Full_Pipeline.pkl']

In [217]:
joblib.load("best_model.pkl") # just to check it is working or not

RandomForestRegressor()

In [219]:
joblib.load("Full_Pipeline.pkl") # same reason

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('Num', StandardScaler())]),
                                 Index(['Rating', 'num_cores', 'num_threads', 'ram_memory',
       'primary_storage_capacity', 'secondary_storage_capacity',
       'resolution_width', 'resolution_height'],
      dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('Cat',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 Index(['brand', 'processor_brand', 'processor_tier', 'primary_storage_type',
       'secondary_storage_type', 'gpu_brand', 'gpu_type', 'OS',
       'year_of_warranty'],
      dtype='object'))])

In [222]:
X.columns.tolist()

['brand',
 'Rating',
 'processor_brand',
 'processor_tier',
 'num_cores',
 'num_threads',
 'ram_memory',
 'primary_storage_type',
 'primary_storage_capacity',
 'secondary_storage_type',
 'secondary_storage_capacity',
 'gpu_brand',
 'gpu_type',
 'is_touch_screen',
 'display_size',
 'resolution_width',
 'resolution_height',
 'OS',
 'year_of_warranty']

In [226]:
# full_pipeline.transform(new_laptop)

In [227]:
full_pipeline.feature_names_in_

array(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit',
       'graphic_card_gb', 'weight', 'display_size', 'warranty',
       'Touchscreen', 'msoffice', 'latest_price', 'star_rating',
       'ratings'], dtype=object)

In [228]:
new_laptop = pd.DataFrame({
    "brand": ["HP"],
    "processor_brand": ["Intel"],
    "processor_name": ["Core i5"],
    "processor_gnrtn": ["12th"],
    "ram_gb": [16],
    "ram_type": ["DDR4"],
    "ssd": [512],
    "hdd": [0],
    "os": ["Windows"],
    "os_bit": [64],
    "graphic_card_gb": [4],
    "weight": ["1.5kg"],
    "display_size": [15.6],
    "warranty": ["1 Year"],
    "Touchscreen": [False],
    "msoffice": [True],
    "latest_price": [70000],
    "star_rating": [4.3],
    "ratings": [100]
})

new_laptop

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,display_size,warranty,Touchscreen,msoffice,latest_price,star_rating,ratings
0,HP,Intel,Core i5,12th,16,DDR4,512,0,Windows,64,4,1.5kg,15.6,1 Year,False,True,70000,4.3,100

In [239]:
# full_pipeline.fit(new_laptop)

In [230]:
set(full_pipeline.feature_names_in_)-set(new_laptop.columns)

set()

In [231]:
set(new_laptop.columns) - set(full_pipeline.feature_names_in_)

set()

In [233]:
full_pipeline = joblib.load("Full_Pipeline.pkl")

In [234]:
full_pipeline.feature_names_in_

array(['brand', 'Rating', 'processor_brand', 'processor_tier',
       'num_cores', 'num_threads', 'ram_memory', 'primary_storage_type',
       'primary_storage_capacity', 'secondary_storage_type',
       'secondary_storage_capacity', 'gpu_brand', 'gpu_type',
       'is_touch_screen', 'display_size', 'resolution_width',
       'resolution_height', 'OS', 'year_of_warranty'], dtype=object)

In [236]:
new_laptop = pd.DataFrame({
    "brand": ["HP"],
    "Rating": [4.3],
    "processor_brand": ["Intel"],
    "processor_tier": ["Core i5"],
    "num_cores": [10],
    "num_threads": [12],
    "ram_memory": [16],
    "primary_storage_type": ["SSD"],
    "primary_storage_capacity": [512],
    "secondary_storage_type": ["None"],
    "secondary_storage_capacity": [0],
    "gpu_brand": ["NVIDIA"],
    "gpu_type": ["Dedicated"],
    "is_touch_screen": [False],
    "display_size": [15.6],
    "resolution_width": [1920],
    "resolution_height": [1080],
    "OS": ["Windows"],
    "year_of_warranty": ["1"]
})

In [237]:
new_laptop.columns.tolist()

['brand',
 'Rating',
 'processor_brand',
 'processor_tier',
 'num_cores',
 'num_threads',
 'ram_memory',
 'primary_storage_type',
 'primary_storage_capacity',
 'secondary_storage_type',
 'secondary_storage_capacity',
 'gpu_brand',
 'gpu_type',
 'is_touch_screen',
 'display_size',
 'resolution_width',
 'resolution_height',
 'OS',
 'year_of_warranty']

In [238]:
new_laptop_prepared = full_pipeline.transform(new_laptop)

In [241]:
predicted_price = best_model.predict(new_laptop_prepared)

print(f"Predicted Laptop Price: ₹{predicted_price[0]:,.2f}")

Predicted Laptop Price: ₹66,116.18

In [242]:
print("----- Laptop Price Prediction Project -----")
print("Best Model: Random Forest Regressor")
print(f"Test RMSE: ₹{20590.01:,.2f}")
print(f"Predicted Price of New Laptop: ₹{predicted_price[0]:,.2f}")

----- Laptop Price Prediction Project -----
Best Model: Random Forest Regressor
Test RMSE: ₹20,590.01
Predicted Price of New Laptop: ₹66,116.18

In [245]:
                                # READ ME

# Laptop Price Prediction using Machine Learning

## Objective

# Predict the price of a laptop based on its specifications using Machine Learning.

## Problem Type

# Supervised Learning - Regression

## Models Used
# - Linear Regression
# - Decision Tree Regressor
# - Random Forest Regressor

## Best Model
# Random Forest Regressor

## Prediction
# The trained model was used to predict the price of a new laptop.

## Technologies Used
# - Python
# - Pandas
# - NumPy
# - Scikit-learn
# - Joblib